os:
  - linux
  - osx

sudo: required
services:
  - docker

language:
  - go
  - node_js

go:
  - 1.9
  - 1.10


after_install:
  - docker build -f travis.dockerfile -t "rpkit:rpkit" ./

script:
  - docker run -it -rm rpkit

